<<<<<<<< HEAD:keyboards/zerfstudios/douballz/keymaps/freznel/graphics/djinn.h
/* Copyright 2021 QMK
========
/* Copyright 2022 Gondolindrim
>>>>>>>> upstream/develop:keyboards/smithrune/iron160/iron160_s/halconf.h
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
<<<<<<<< HEAD:keyboards/zerfstudios/douballz/keymaps/freznel/graphics/djinn.h
 * This file was auto-generated by `qmk painter-convert-graphics -i djinn.png -f mono16`
========
 * This file was auto-generated by:
 *    `qmk chibios-confmigrate -i keyboards/iron180/halconf.h -r platforms/chibios/common/configs/halconf.h`
>>>>>>>> upstream/develop:keyboards/smithrune/iron160/iron160_s/halconf.h
 */

#pragma once

<<<<<<<< HEAD:keyboards/zerfstudios/douballz/keymaps/freznel/graphics/djinn.h
#include <qp.h>

extern painter_image_t gfx_djinn PROGMEM;
========
#define HAL_USE_PWM TRUE

#include_next <halconf.h>
>>>>>>>> upstream/develop:keyboards/smithrune/iron160/iron160_s/halconf.h
