<<<<<<<< HEAD:keyboards/zerf9/space_control1/testchconf.h
/* Copyright 2020 QMK
========
/* Copyright 2023 Guillermo Aguirre
>>>>>>>> upstream/develop:keyboards/preonic/keymaps/guillermoap/config.h
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

<<<<<<<< HEAD:keyboards/zerf9/space_control1/testchconf.h
/*
 * This file was auto-generated by:
 *    `qmk chibios-confmigrate -i keyboards/handwired/onekey/blackpill_f411/chconf.h -r platforms/chibios/common/configs/chconf.h`
 */

#pragma once
#define CH_CFG_ST_FREQUENCY 10000

#define CH_CFG_ST_TIMEDELTA 0

#define CH_CFG_TIME_QUANTUM 20

// #define CH_CFG_FACTORY_OBJECTS_REGISTRY TRUE

// #define CH_CFG_FACTORY_GENERIC_BUFFERS TRUE

// #define CH_CFG_FACTORY_SEMAPHORES TRUE

// #define CH_CFG_FACTORY_MAILBOXES TRUE

// #define CH_CFG_FACTORY_OBJ_FIFOS TRUE

// #define CH_CFG_FACTORY_PIPES TRUE

#include_next <chconf.h>
========
#pragma once

#ifdef AUDIO_ENABLE
#    define STARTUP_SONG SONG(PREONIC_SOUND)
// #define STARTUP_SONG SONG(NO_SOUND)

#    define DEFAULT_LAYER_SONGS \
        { SONG(QWERTY_SOUND), SONG(COLEMAK_SOUND), SONG(DVORAK_SOUND) }
#endif

#define MUSIC_MASK (keycode != KC_NO)

/*
 * MIDI options
 */

/* enable basic MIDI features:
   - MIDI notes can be sent when in Music mode is on
*/

#define MIDI_BASIC

/* enable advanced MIDI features:
   - MIDI notes can be added to the keymap
   - Octave shift and transpose
   - Virtual sustain, portamento, and modulation wheel
   - etc.
*/
//#define MIDI_ADVANCED
>>>>>>>> upstream/develop:keyboards/preonic/keymaps/guillermoap/config.h
