POINTING_DEVICE_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
# POINTING_DEVICE_DRIVERS += ps2_trackpoint
POINTING_DEVICE_DRIVERS +=  azoteq_iqs5xx

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
# PS2_ENABLE = yes
# PS2_MOUSE_ENABLE = yes
# PS2_DRIVER = vendor

