POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = ps2_trackpoint
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
PS2_ENABLE = yes
PS2_MOUSE_ENABLE = yes
PS2_DRIVER = vendor
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

